kind: pipeline
name: default

trigger:
  event:
    - push


steps:
- image: python:3.7-alpine
  name: test
  environment:
    username:
      from_secret: username
    password:
      from_secret: password
  commands:
  - apk add --no-cache build-base git > /dev/null
  - pip install ./src  > /dev/null
  - pip install pytest pytest-asyncio > /dev/null
  - pytest -sv -x
- name: bump
  image: xplugins/bump
  settings:
    github_token: 
      from_secret: github_token
    versionfile: src/VERSION
- name: pypi_publish
  image: plugins/pypi
  settings:
    username: xmorse
    setupfile: src/setup.py
    password:
      from_secret: pypi_password
    distributions:
      - sdist
      - bdist_wheel
